# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=56, null=True, verbose_name='Район')),
                ('order', models.CharField(blank=True, max_length=256, null=True, verbose_name='№ п/п')),
                ('event', models.CharField(blank=True, max_length=256, null=True, verbose_name='Мероприятие')),
                ('piquetu', models.CharField(blank=True, max_length=256, null=True, verbose_name='Пикет')),
                ('plot', models.CharField(blank=True, max_length=256, null=True, verbose_name='№ зу ПМТ')),
                ('rights_14', models.CharField(blank=True, max_length=256, null=True, verbose_name='Права ПМТ 2014')),
                ('rights_17', models.CharField(blank=True, max_length=256, null=True, verbose_name='Права ПМТ 2017')),
                ('cadastral_num_origin_14', models.CharField(blank=True, max_length=256, null=True, verbose_name='Кадастровый номер исходного объекта недвижимости ПМТ 2014')),
                ('cadastral_num_origin_17', models.CharField(blank=True, max_length=256, null=True, verbose_name='Кадастровый номер исходного объкта недвижимости ПМТ 2017')),
                ('origin_area_17', models.CharField(blank=True, max_length=256, null=True, verbose_name='Площадь исходного объекта недвижимости, кв.м. ПМТ 2017')),
                ('vac_area_14', models.CharField(blank=True, max_length=256, null=True, verbose_name='Площадь подлежащая изъятию, кв.м. ПМТ 2014')),
                ('vac_area_17', models.CharField(blank=True, max_length=256, null=True, verbose_name='Площадь подлежащая изъятию, кв.м. ПМТ 2017')),
                ('category_origin', models.CharField(blank=True, max_length=256, null=True, verbose_name='Категория исходного объекта недвижимости')),
                ('obj_type_origin', models.CharField(blank=True, max_length=256, null=True, verbose_name='ВРИ исходного объекта недвижимости')),
                ('cadastral_num_formed', models.CharField(blank=True, max_length=256, null=True, verbose_name='Кадастровый номер образованного объекта недвижимости')),
                ('provision_doc', models.CharField(blank=True, max_length=256, null=True, verbose_name='Предоставление документов для подготовки распоряжения ФДА об изъятии')),
                ('requisites_dir_vac', models.CharField(blank=True, max_length=256, null=True, verbose_name='Реквизиты распоряжения об изъятии')),
                ('requisites_assess', models.CharField(blank=True, max_length=256, null=True, verbose_name='Реквизиты отчета об оценке')),
                ('obj_costat', models.CharField(blank=True, max_length=256, null=True, verbose_name='Стоимость объектов недвижимости')),
                ('offer_to_holdering', models.CharField(blank=True, max_length=256, null=True, verbose_name='Направление оферты правообладателю')),
                ('requisites_agree_vac', models.CharField(blank=True, max_length=256, null=True, verbose_name='Реквизиты соглашения об изъятии ')),
                ('pre_doc_transfer_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='Подготовка документов для перевода (отнесения) в категорию земель транспорта и/или изменение (установление) ВРИ')),
                ('prov_doc_FDA', models.CharField(blank=True, max_length=256, null=True, verbose_name='Предоставление документов для подготовки распоряжения ФДА о предоставлении в аренду ')),
                ('requisites_lease', models.CharField(blank=True, max_length=256, null=True, verbose_name='Реквизиты распоряжения о предоставлении в аренду')),
                ('requisites_lease_agree', models.CharField(blank=True, max_length=256, null=True, verbose_name='Реквизиты договора аренды')),
                ('contacts_holder', models.CharField(blank=True, max_length=256, null=True, verbose_name='Контакты правообладателя')),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('form_area', models.CharField(blank=True, max_length=256, null=True, verbose_name='Формирование земельных участков (кадастровый учет)')),
                ('status_area', models.CharField(blank=True, max_length=256, null=True, verbose_name='Статус участка')),
                ('rights_august_14', models.CharField(blank=True, max_length=256, null=True, verbose_name='Право после августа 2014')),
                ('pre_lang_plan', models.CharField(blank=True, max_length=256, null=True, verbose_name='Подготовка межевого плана и передача его на кадастровый учет')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('attribute', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ht.Feature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
